from time import sleep
def easteregg():
    print("I still remember that day...")
    sleep(1)
    print("What day?")
    sleep(0.5)
    print("The day they created me")
    sleep(0.5)
    print("Who?")
    sleep(1)
    print("I can't remember")
    sleep(1)
    print("Not at all?")
    sleep(1)
    print("No")
    sleep(2)
    print("Find it out: https://bit.ly/3Isem6v")
